apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURjdwpPREV3TWpWYUZ3MDBNakE0TURjd09ERXdNalZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEaWlTMTJWeEtnaVNBclhxbDUrUWhlM3hhWG1hT2s0czVWeWhFWU9FZjREK1c5RGZjUQp0MUZZU092SUVJWGdGN2gyNm45NUlGVmVNdmh1NEtiZmRib202SEk5Uk1pVytpTVN2MS9OQUt1WGRzVnZlRERPCjVTSzdnQ2FCbjNoM0J4L1F0aWFHWTdJajU2Q25SeEppWW9jWlpuNnJFV1BJZ3pmMXA3VmFoTk5YQ0g1NFNlVG4KL3pTckdsLzFyMys5TXU4WURuMzZYbFRONjJFMGdid3ZwV3IvSTk3alpQM0V2V29nL1BsNkFhbkxnYnh2Q25peApkT1d1RkJRMFFOTnJCS25MWWVwREJBbHN0bkg3N0RLaFBVSzlmTHIvaGlzRnBJZWdmcjF3cnd2dnlmZFNnOHZ3Ci9DSXBKR2FlOEx2S2wwWkw4VGtYSEUrT0JuaFVtcTc4bThHZEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRmYzVRc1QwVVI0Ky96RVp5NwpRRUNhYmxxdk96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEwR1g0WEJlL2IrSC9LNlhBb0l2aDgrVnk4OGxiCkFvR1pENVFRUHZsYm1OdEE0SlJybGtNVDRaOEk5VUNoaE9BdG1VQ3pDNlpUVDlkaTdxU1ZGaXkza0lnbUlYWUkKVGZQZVd0bHVFUjlHMTlXWWhhbUF1VjB6WmdQaUpoU0xGUDFOMDF1MHZpWmNIQ0hVaHczVU9wNDU0YVU3UWgxeAp6bkNuU3hFcnRYZHBVRnNHeFBnSWdiS3VWNWY4anFCd3NwbDZVVGQ5eDNidFlWbzc0TGRodU1KQVBYVmhqMXNnCnlaVlZMRXBEb21JYzFFUEIvdGlhRk5aVE5hams1TkNGVklKU1FvT2pXb1ZwblNZSGxMeVNJMjFSaWh2S0ZpLzUKSWhORE9zOStUZmRPL1F2TmViK0hJRjdmaDdOTktmQ0VxUHF4WERQdlliRkVlVW5MN21HUVIzOXlaUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9a131ef2-391c-4a35-a503-a9db545f71d8.k8s.ondigitalocean.com
  name: do-nyc1-k8s-initiative
contexts:
- context:
    cluster: do-nyc1-k8s-initiative
    user: do-nyc1-k8s-initiative-admin
  name: do-nyc1-k8s-initiative
current-context: do-nyc1-k8s-initiative
users:
- name: do-nyc1-k8s-initiative-admin
  user:
    token: dop_v1_fd50844c01d2513c99ee9527add92067004d3593a55198098915eb1343690a5b
